proc format;
value AABEER5Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AABEERFf 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AAFWIN1Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AALCG5f 1 ="No " 
    2 ="Yes ";
value AALCUSEf 1 ="Formerly used alcohol products " 
    2 ="Currently use alcohol products " 
    3 ="Never used alcohol products ";
value AALIQ1Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AALIQ2Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AALIQ3Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AALIQ5Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AASPR30Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AASPR50Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AAWIN1Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value AAWIN2Ff 1 ="Daily " 
    2 ="Weekly " 
    3 ="Monthly ";
value ABBANKDf 0 ="Blank " 
    1 ="Checked ";
value ABFFOODDf 0 ="Blank " 
    1 ="Checked ";
value ABFREPOLf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABFRESTDf 0 ="Blank " 
    1 ="Checked ";
value ABGROCDf 0 ="Blank " 
    1 ="Checked ";
value ABHIGCRMf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABLOODf 1 ="No " 
    2 ="Yes ";
value ABLOODTf 1 ="Fasting sample " 
    2 ="Non-fasting sample ";
value ABNUTUSEf 1 ="Formerly used betel nut products " 
    2 ="Currently use betel nut products " 
    3 ="Never used betel nut products ";
value ABPEPWLKf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABPOFFDf 0 ="Blank " 
    1 ="Checked ";
value ABREGSHPf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABRFEEDf 1 ="No " 
    2 ="Yes ";
value ABRPRBDOGf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABSPKWLKf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABSTRWELf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ABVSTORDf 0 ="Blank " 
    1 ="Checked ";
value ABWLKDIFf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value ACAREORPf 1 ="No " 
    2 ="Yes ";
value ACARMROBf 0 ="Blank " 
    1 ="Checked ";
value ACCLDABUf 0 ="Blank " 
    1 ="Checked ";
value ACCLDSEXf 0 ="Blank " 
    1 ="Checked ";
value ACHOUBRKf 0 ="Blank " 
    1 ="Checked ";
value ACIVORGOPf 1 ="none " 
    2 ="little " 
    3 ="moderate/average " 
    4 ="a great deal ";
value ACMURDERf 0 ="Blank " 
    1 ="Checked ";
value ACOTHERf 0 ="Blank " 
    1 ="Checked ";
value ACOUGH3Mf 1 ="No " 
    2 ="Yes ";
value ACPERIORf 1 ="No " 
    2 ="Yes ";
value ACRAPEf 0 ="Blank " 
    1 ="Checked ";
value ACRIM5Yf 1 ="No " 
    2 ="Yes ";
value ACTHEFTf 0 ="Blank " 
    1 ="Checked ";
value ACURPREGf 1 ="No " 
    2 ="Yes ";
value ACVEHHIJf 0 ="Blank " 
    1 ="Checked ";
value ACVIOATTf 0 ="Blank " 
    1 ="Checked ";
value ACWOMABUf 0 ="Blank " 
    1 ="Checked ";
value ADAIDSf 1 ="No " 
    2 ="Yes " 
    3 ="Not answered ";
value ADASTHf 1 ="No " 
    2 ="Yes ";
value ADASTHHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADBENDf 1 ="No " 
    2 ="Yes ";
value ADBENDCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADCANCf 1 ="No " 
    2 ="Yes ";
value ADCANCHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADCANCSf 1 ="Mouth " 
    2 ="Esophagus " 
    3 ="Stomach " 
    4 ="Small intestine " 
    5 ="Large intestine including rectum " 
    6 ="Pancreas " 
    7 ="Liver " 
    8 ="Lung " 
    9 ="Breast " 
    10 ="Cervical/ uterine/ ovarian " 
    11 ="Prostate " 
    12 ="Head and neck " 
    13 ="Other, specify ";
value ADCHAGf 1 ="No " 
    2 ="Yes ";
value ADCHDf 1 ="No " 
    2 ="Yes ";
value ADCHDHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADCOPDf 1 ="No " 
    2 ="Yes ";
value ADCOPDHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADDIABf 1 ="No " 
    2 ="Yes ";
value ADDIABHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADEPRESSf 1 ="No " 
    2 ="Yes ";
value ADFCANCf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADFCANCSf 1 ="Mouth " 
    2 ="Esophagus " 
    3 ="Stomach " 
    4 ="Small intestine " 
    5 ="Large intestine including rectum " 
    6 ="Pancreas " 
    7 ="Liver " 
    8 ="Lung " 
    9 ="Breast " 
    10 ="Cervical/ uterine/ ovarian " 
    11 ="Prostate " 
    12 ="Head and neck " 
    13 ="Other, specify ";
value ADFCHDf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADFDIABf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADFELDOWf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADFELTIRf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADFHBPf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADFSTRKf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADGAIWGf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADGRASPf 1 ="No " 
    2 ="Yes ";
value ADGRASPCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADHEARf 1 ="No " 
    2 ="Yes ";
value ADHEARCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADHEPAf 1 ="No " 
    2 ="Yes ";
value ADHEPAHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADHFAILf 1 ="No " 
    2 ="Yes ";
value ADHFAILHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADHYPEf 1 ="No " 
    2 ="Yes ";
value ADHYPEHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADLOSINTf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADMALAf 1 ="No " 
    2 ="Yes ";
value ADMCANCf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADMCANCSf 1 ="Mouth " 
    2 ="Esophagus " 
    3 ="Stomach " 
    4 ="Small intestine " 
    5 ="Large intestine including rectum " 
    6 ="Pancreas " 
    7 ="Liver " 
    8 ="Lung " 
    9 ="Breast " 
    10 ="Cervical/ uterine/ ovarian " 
    11 ="Prostate " 
    12 ="Head and neck " 
    13 ="Other, specify ";
value ADMCHDf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADMDIABf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADMEDASTHf 1 ="No " 
    2 ="Yes ";
value ADMEDBPf 1 ="No " 
    2 ="Yes ";
value ADMEDCC1Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC2Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC3Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC4Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC5Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC6Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC7Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCC8Pf 1 ="MOH clinic " 
    2 ="UNRWA clinic pharmacy " 
    3 ="Private pharmacy " 
    4 ="NGO clinic pharmacy " 
    5 ="Other ";
value ADMEDCHINf 1 ="No " 
    2 ="Yes ";
value ADMEDCLDf 1 ="No " 
    2 ="Yes ";
value ADMEDCUTBCKf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ADMEDDIABf 1 ="No " 
    2 ="Yes ";
value ADMEDFORGETf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ADMEDHASSLEDf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ADMEDOTf 1 ="No " 
    2 ="Yes ";
value ADMEDRf 1 ="No " 
    2 ="Yes ";
value ADMEDSKIPf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ADMEDSTOPf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ADMEDSTRf 1 ="No " 
    2 ="Yes ";
value ADMEDUNKf 1 ="No " 
    2 ="Yes ";
value ADMHBPf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADMSTRKf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADOHDf 1 ="No " 
    2 ="Yes ";
value ADOHDHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADREADf 1 ="No " 
    2 ="Yes ";
value ADSCANCf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADSCANCSf 1 ="Mouth " 
    2 ="Esophagus " 
    3 ="Stomach " 
    4 ="Small intestine " 
    5 ="Large intestine including rectum " 
    6 ="Pancreas " 
    7 ="Liver " 
    8 ="Lung " 
    9 ="Breast " 
    10 ="Cervical/ uterine/ ovarian " 
    11 ="Prostate " 
    12 ="Head and neck " 
    13 ="Other, specify ";
value ADSCHDf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADSDIABf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADSEEPf 1 ="No " 
    2 ="Yes ";
value ADSEEPCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADSHBPf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADSPEAKf 1 ="No " 
    2 ="Yes ";
value ADSPEAKCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADSSTRKf 1 ="No " 
    2 ="Yes " 
    3 ="Unknown ";
value ADSTICKf 1 ="No " 
    2 ="Yes ";
value ADSTICKCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ADSTROKf 1 ="No " 
    2 ="Yes ";
value ADSTROKHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADTDEATf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADTRBCONf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADTRBSLEf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value ADTUBERf 1 ="No " 
    2 ="Yes ";
value ADTUBERHPf 1 ="MOH " 
    2 ="UNRWA " 
    3 ="Private ";
value ADWALKf 1 ="No " 
    2 ="Yes ";
value ADWALKCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value AEARMCONf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEBIRFAMf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AECGf 1 ="No " 
    2 ="Yes ";
value AEDTHAFMf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEDTHSPOf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEFAMCONf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEHHLDBRf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AELOSCRPf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AELOSJOBf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEMARSEPf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEMPLOYf 1 ="No " 
    2 ="Yes ";
value AENEWJOBf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AENOFOODf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEOTHSTRf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEPERINJf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AERETIREf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AESEPFAMf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AETHNICf 1 ="South Asian (India, Sri Lanka, Pakistan, Bangladesh) " 
    2 ="Chinese (China, Hong Kong, Taiwan) " 
    3 ="Japanese " 
    4 ="Malays " 
    5 ="Other Asian (Korea, Malaysia, Papua New Guinea, Thailand, Philippines, Indonesia, Nepal, Vietnam, C " 
    6 ="Persian " 
    7 ="Arab " 
    8 ="Black African " 
    9 ="Coloured African (Subsaharan African only) " 
    10 ="European " 
    11 ="Native North/South American or Australian Aborigine (Indigenous) " 
    12 ="Latin American (Latino) " 
    13 ="Bantu/ Semi Bantu " 
    14 ="Hemitic/ Semi Hemitic " 
    15 ="Nilotic/ Hausa " 
    16 ="Pygmie " 
    17 ="Swahili " 
    18 ="Other (any other ethnoracial group not listed above) " 
    19 ="Han " 
    20 ="Wei " 
    21 ="Meng " 
    22 ="Chaoxian " 
    23 ="Zang " 
    24 ="Man " 
    25 ="Hui " 
    26 ="Xibo " 
    27 ="HaNi " 
    28 ="Dai " 
    29 ="Yi " 
    30 ="Mestizo " 
    31 ="Montubio ";
value AEVIOLENf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEWEDFAMf 1 ="No " 
    2 ="Yes " 
    3 ="No response ";
value AEYELf 1 ="Normal/ other " 
    2 ="Blindness due to causes other than cataracts " 
    3 ="Immature cataract " 
    4 ="Mature cataract " 
    5 ="Operated due to cataract ";
value AEYERf 1 ="Normal/ other " 
    2 ="Blindness due to causes other than cataracts " 
    3 ="Immature cataract " 
    4 ="Mature cataract " 
    5 ="Operated due to cataract ";
value AFAMMEMOPf 1 ="none " 
    2 ="little " 
    3 ="moderate/average " 
    4 ="a great deal ";
value AFEDUCf 1 ="None " 
    2 ="Primary " 
    3 ="Secondary/High School/Higher Secondary " 
    4 ="Trade School " 
    5 ="College/University " 
    6 ="Unknown ";
value AFRUCTURf 1 ="No " 
    2 ="Yes ";
value AFSITE1f 1 ="Hip/pelvis " 
    2 ="Thigh " 
    3 ="Leg " 
    4 ="Forearm " 
    5 ="Wrist " 
    6 ="Hand/finger " 
    7 ="Vertebrae (back) " 
    8 ="Other ";
value AFSITE2f 1 ="Hip/pelvis " 
    2 ="Thigh " 
    3 ="Leg " 
    4 ="Forearm " 
    5 ="Wrist " 
    6 ="Hand/finger " 
    7 ="Vertebrae (back) " 
    8 ="Other ";
value AFSITE3f 1 ="Hip/pelvis " 
    2 ="Thigh " 
    3 ="Leg " 
    4 ="Forearm " 
    5 ="Wrist " 
    6 ="Hand/finger " 
    7 ="Vertebrae (back) " 
    8 ="Other ";
value AGLASSf 1 ="No " 
    2 ="Yes ";
value AHAMAGEf 1 ="Younger than 10 years " 
    2 ="Between 11-20 years " 
    3 ="Between 21-30 years " 
    4 ="Between 31-40 years " 
    5 ="Between 41-50 years " 
    6 ="Over 50 years ";
value AHAPCOMMf 0 ="Blank " 
    1 ="Checked ";
value AHAYCLDf 0 ="Blank " 
    1 ="Checked ";
value AHAYFMEMf 0 ="Blank " 
    1 ="Checked ";
value AHAYFRNDf 0 ="Blank " 
    1 ="Checked ";
value AHAYGCLDf 0 ="Blank " 
    1 ="Checked ";
value AHAYSPOUf 0 ="Blank " 
    1 ="Checked ";
value AHEAIDf 1 ="No " 
    2 ="Yes ";
value AHELMDRf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value AHELMPASf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value AHIVAIDSf 1 ="No " 
    2 ="Yes ";
value AHLEDUCf 1 ="Illiterate " 
    2 ="Primary " 
    3 ="Secondary " 
    4 ="High school " 
    5 ="Higher secondary " 
    6 ="College/University " 
    7 ="Unknown ";
value AHMEMCOf 1 ="No " 
    2 ="Yes ";
value AHPRCARCCf 0 ="Blank " 
    1 ="Checked ";
value AHPRCARFMf 0 ="Blank " 
    1 ="Checked ";
value AHPRCARFRf 0 ="Blank " 
    1 ="Checked ";
value AHPRCARPAf 0 ="Blank " 
    1 ="Checked ";
value AHPRCARSPf 0 ="Blank " 
    1 ="Checked ";
value AHPRCARVOf 0 ="Blank " 
    1 ="Checked ";
value AIACCMf 1 ="No " 
    2 ="Yes ";
value AIACCMLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIACCMTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIACONFf 1 ="No " 
    2 ="Yes ";
value AIACONFLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIACONFTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIASUICf 1 ="No " 
    2 ="Yes ";
value AIASUICLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIASUICTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AICRUSHf 1 ="No " 
    2 ="Yes ";
value AICRUSHLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AICRUSHTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIDROWf 1 ="No " 
    2 ="Yes ";
value AIDROWLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIDROWTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIDVIOLf 1 ="No " 
    2 ="Yes ";
value AIDVIOLLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIDVIOLTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIEXPLf 1 ="No " 
    2 ="Yes ";
value AIEXPLLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIEXPLTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIFALLf 1 ="No " 
    2 ="Yes ";
value AIFALLLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIFALLTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIFIREf 1 ="No " 
    2 ="Yes ";
value AIFIRELf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIFIRETf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIHCLIQf 1 ="No " 
    2 ="Yes ";
value AIHCLIQLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIHCLIQTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIMOPAf 1 ="No " 
    2 ="Yes ";
value AIMOPALf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIMOPATf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIMOPEf 1 ="No " 
    2 ="Yes ";
value AIMOPELf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIMOPETf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AINENVf 1 ="No " 
    2 ="Yes ";
value AINENVLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AINENVTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AINJURYf 1 ="No " 
    2 ="Yes ";
value AIOTHf 1 ="No " 
    2 ="Yes ";
value AIOTHLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIOTHTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIPASSf 1 ="No " 
    2 ="Yes ";
value AIPASSLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIPASSTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AIPOISf 1 ="No " 
    2 ="Yes ";
value AIPOISLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AIPOISTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AISNAKf 1 ="No " 
    2 ="Yes ";
value AISNAKLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AISNAKTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AISTRUf 1 ="No " 
    2 ="Yes ";
value AISTRULf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AISTRUTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AISUFFf 1 ="No " 
    2 ="Yes ";
value AISUFFLf 1 ="Factory/ industrial place " 
    2 ="Office " 
    3 ="Agriculture field/farm " 
    4 ="Home " 
    5 ="Road " 
    6 ="Sport/ game e.g. track, court, field, etc. " 
    7 ="Public building " 
    8 ="Mine/quarry " 
    9 ="Construction site e.g. building, road-works, etc. " 
    10 ="Other ";
value AISUFFTf 1 ="Burns " 
    2 ="Scalds " 
    3 ="Fractures " 
    4 ="Muscle and Ligament sprains/tears " 
    5 ="Cuts and lacerations " 
    6 ="Bruises and abrasions " 
    7 ="Suffocation " 
    8 ="Head injury (where person did not lose consciousness) " 
    9 ="Head Injury (where person lost consciousness for some time) ";
value AMARSTf 1 ="Never married " 
    2 ="Currently married " 
    3 ="Common law/living with partner " 
    4 ="Widowed " 
    5 ="Separated " 
    6 ="Divorced ";
value AMEMOTHf 1 ="No " 
    2 ="Yes ";
value AMEMRELf 1 ="No " 
    2 ="Yes ";
value AMEMSOCf 1 ="No " 
    2 ="Yes ";
value AMHBACNECf 1 ="No " 
    2 ="Yes ";
value AMHBREATHf 1 ="No " 
    2 ="Yes ";
value AMHBSPUTf 1 ="No " 
    2 ="Yes ";
value AMHBURINEf 1 ="No " 
    2 ="Yes ";
value AMHBURNUf 1 ="No " 
    2 ="Yes ";
value AMHCOUGHf 1 ="No " 
    2 ="Yes ";
value AMHCPAINf 1 ="No " 
    2 ="Yes ";
value AMHCSPUTf 1 ="No " 
    2 ="Yes ";
value AMHDIARRf 1 ="No " 
    2 ="Yes ";
value AMHJAUNDf 1 ="No " 
    2 ="Yes ";
value AMHLAPPETf 1 ="No " 
    2 ="Yes ";
value AMHPTETHf 1 ="No " 
    2 ="Yes ";
value AMHSFACEf 1 ="No " 
    2 ="Yes ";
value AMHSFEETf 1 ="No " 
    2 ="Yes ";
value AMHVOMITf 1 ="No " 
    2 ="Yes ";
value AMHWHEEZf 1 ="No " 
    2 ="Yes ";
value AMHWLOSSf 1 ="No " 
    2 ="Yes ";
value AMOCUPGf 1 ="Group 1 - Legislators, senior officials and managers " 
    2 ="Group 2 - Professionals " 
    3 ="Group 3 - Technicians and associate professionals " 
    4 ="Group 4 - Clerks " 
    5 ="Group 5 - Service workers and shop and market sales workers " 
    6 ="Group 6 - Skilled agricultural and fishery workers " 
    7 ="Group 7 - Craft and related trade workers " 
    8 ="Group 8 - Plant and machine operators and assemblers " 
    9 ="Group 9 - Elementary occupations " 
    10 ="Group 10 - Armed forces " 
    11 ="Group 11 - Homemaker ";
value ANAIDNAf 0 ="Blank " 
    1 ="Checked ";
value ANAPf 1 ="No " 
    2 ="Yes ";
value ANATGf 1 ="Kazakh " 
    2 ="Kyrgyz " 
    3 ="Russian " 
    4 ="Turkmen " 
    5 ="Ukrainian " 
    6 ="Tatar " 
    7 ="Jews " 
    8 ="Tajic " 
    9 ="Uzbek " 
    10 ="Other ";
value ANOEXREf 1 ="Bad weather " 
    2 ="Lack of transportation to walking areas " 
    3 ="Health barriers " 
    4 ="Absence of walking/sport facilities " 
    5 ="Busy lifestyle (not enough time) " 
    6 ="Not interested " 
    7 ="Other ";
value AOPEALCf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPECIGf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPEFLOURf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPEHONf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value AOPEOILf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPERICEf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPESDRf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPESNKf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree " 
    5 ="Not Applicable ";
value AOPETREf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value AORALCONf 1 ="No " 
    2 ="Yes ";
value AOTHEROPf 1 ="none " 
    2 ="little " 
    3 ="moderate/average " 
    4 ="a great deal ";
value APMHCLTf 1 ="Minimal/no clothing " 
    2 ="Full clothing ";
value APMWCLTf 1 ="Minimal/no clothing " 
    2 ="Full clothing ";
value APMWSCLTf 1 ="Minimal/no clothing " 
    2 ="Full clothing ";
value AREADCf 1 ="accident " 
    2 ="leprosy " 
    3 ="polio " 
    4 ="stroke " 
    5 ="congenital " 
    6 ="aging " 
    7 ="Physical assault/ Violent crime " 
    8 ="Armed conflict " 
    9 ="Domestic violence " 
    10 ="Other ";
value ARELIGf 1 ="Christianity " 
    2 ="Hinduism " 
    3 ="Islam " 
    4 ="Buddhism " 
    5 ="Judaism " 
    6 ="Atheist/Agnostic " 
    7 ="Sikkhism " 
    8 ="Traditional Chinese " 
    9 ="None " 
    10 ="Other ";
value ARELORGOPf 1 ="none " 
    2 ="little " 
    3 ="moderate/average " 
    4 ="a great deal ";
value ARETIREDf 1 ="No " 
    2 ="Yes ";
value ASEATDRf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ASEATPASf 1 ="No " 
    2 ="Yes " 
    3 ="Not applicable ";
value ASEXf 1 ="Female " 
    2 ="Male ";
value ASPFEV1Af 1 ="No " 
    2 ="Yes ";
value ASPFEV1R1f 0 ="Blank " 
    1 ="Checked ";
value ASPFEV1R2f 0 ="Blank " 
    1 ="Checked ";
value ASPFEV1R3f 0 ="Blank " 
    1 ="Checked ";
value ASPFVCAf 1 ="No " 
    2 ="Yes ";
value ASPFVCR1f 0 ="Blank " 
    1 ="Checked ";
value ASPFVCR2f 0 ="Blank " 
    1 ="Checked ";
value ASPFVCR3f 0 ="Blank " 
    1 ="Checked ";
value ASPPEFREf 1 ="No " 
    2 ="Yes ";
value ASPPEFRR1f 0 ="Blank " 
    1 ="Checked ";
value ASPPEFRR2f 0 ="Blank " 
    1 ="Checked ";
value ASTRHOMEf 1 ="No response " 
    2 ="Never Experienced Stress " 
    3 ="Some Period of Stress " 
    4 ="Several Periods of Stress " 
    5 ="Permanent Stress ";
value ASTRLEVLf 1 ="No response " 
    2 ="Little/none " 
    3 ="Moderate " 
    4 ="High/severe ";
value ASTRWNAf 0 ="Blank " 
    1 ="Checked ";
value ASTRWORKf 1 ="No response " 
    2 ="Never Experienced Stress " 
    3 ="Some Period of Stress " 
    4 ="Several Periods of Stress " 
    5 ="Permanent Stress ";
value ASTWORKf 1 ="No " 
    2 ="Yes ";
value ATOBUSEf 1 ="Formerly Used Tobacco Products " 
    2 ="Currently Uses Tobacco Products " 
    3 ="Never Used Tobacco Products ";
value ATSMOKEf 1 ="No " 
    2 ="Yes ";
value ATSMTYPf 1 ="1-2 times/week " 
    2 ="3-6 times/week " 
    3 ="at least once a day " 
    4 ="2-3 times/day " 
    5 ="4 or more times/day ";
value AURINEf 1 ="No " 
    2 ="Yes ";
value AURINETf 1 ="Fasting sample " 
    2 ="Non-fasting sample ";
value AVARMROBf 1 ="No " 
    2 ="Yes ";
value AVCLDABUf 1 ="No " 
    2 ="Yes ";
value AVCLDSEXf 1 ="No " 
    2 ="Yes ";
value AVHOUBRKf 1 ="No " 
    2 ="Yes ";
value AVMURDERf 1 ="No " 
    2 ="Yes ";
value AVOTHERf 1 ="No " 
    2 ="Yes ";
value AVRAPEf 1 ="No " 
    2 ="Yes ";
value AVTHEFTf 1 ="No " 
    2 ="Yes ";
value AVVEHHIJf 1 ="No " 
    2 ="Yes ";
value AVVIOATTf 1 ="No " 
    2 ="Yes ";
value AVWOMABUf 1 ="No " 
    2 ="Yes ";
value CAALWSHUNGf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAANXSEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAAVDEATf 1 ="almost never " 
    2 ="seldom " 
    3 ="usually " 
    4 ="almost always ";
value CABLUEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CACHIPSf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CACOOKIEf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CACTRLWTf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CADELIEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAEATANYTMf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAEATBINGEf 1 ="Never " 
    2 ="Rarely " 
    3 ="Sometimes " 
    4 ="At least once a week ";
value CAEATLESSf 1 ="unlikely " 
    2 ="slightly unlikely " 
    3 ="moderately likely " 
    4 ="very likely ";
value CAEATSCALEf 1 ="1 " 
    2 ="2 " 
    3 ="3 " 
    4 ="4 " 
    5 ="5 " 
    6 ="6 " 
    7 ="7 " 
    8 ="8 ";
value CAEXERCISEf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CAFISHf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CAFLHUNGf 1 ="only at meal times " 
    2 ="sometimes between meals " 
    3 ="often between meals " 
    4 ="almost always ";
value CAFRUTVEGf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CAHDSPEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAHUNGRYf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CALONEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAMEATf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value CANOEATFATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CANOGAINWTf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CAOEATHUNGf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CASMLEATf 1 ="Definitely false " 
    2 ="Mostly false " 
    3 ="Mostly true " 
    4 ="Definitely true ";
value CASODAf 1 ="Strongly Disagree " 
    2 ="Somewhat Disagree " 
    3 ="Somewhat Agree " 
    4 ="Strongly Agree ";
value v3aspirdnf 1 ="No " 
    2 ="Yes ";
value v3aspirnof 1 ="Participant Refused " 
    2 ="Participant not able to perform spirometry tests " 
    3 ="Telephone/Mail-out visit only " 
    4 ="Other ";
value v3cholestuf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3creauf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3glucoseuf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3haemuf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3hdluf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3ldluf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3potuf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3soduf 1 ="mg/dL " 
    2 ="mmol/L ";
value v3spirdnf 1 ="No " 
    2 ="Yes ";
value v3spirnewf 0 ="Blank " 
    1 ="Checked ";
value v3spirnof 1 ="Participant Refused " 
    2 ="Participant not able to perform spirometry tests " 
    3 ="Telephone/Mail-out visit only " 
    4 ="Other ";
value v3spiroldf 0 ="Blank " 
    1 ="Checked ";
value v3spqugrdf 1 ="Grade A " 
    2 ="Grade B " 
    3 ="Grade C " 
    4 ="Grade D " 
    5 ="Grade F " 
    6 ="No grade provided ";
value v3sptstcd1f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd2f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd3f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd4f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd5f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd6f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd7f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3sptstcd8f 1 ="Don't hesitate " 
    2 ="Blast out faster " 
    3 ="Blow out longer " 
    4 ="Good effort, do next " 
    5 ="Blast out harder(only in frontline mode) " 
    6 ="Wait until buzz before blowing out " 
    7 ="Cough detected, try again " 
    8 ="Deeper breath " 
    9 ="Test complete ";
value v3triglycuf 1 ="mg/dL " 
    2 ="mmol/L ";
